version: 2.6.1.{build}

branches:
  only:
    - develop
    - /release\/.*/

skip_tags: true
max_jobs: 1
image: Ubuntu1604
stack: jdk 8, python 3

build_script:
  - python3 -m pip install mkdocs mkdocs-material
  - [[ "$APPVEYOR_REPO_BRANCH" == "release/"* ]] && BUILD_DOCKER=buildDocker ; ./gradlew buildJar buildCli buildDoc $BUILD_DOCKER -PbuildNumber=${APPVEYOR_BUILD_NUMBER} -PnoTest
  - ./gradlew jacocoTestReport
  - bash <(curl -s https://codecov.io/bash)
  - ./publish.sh
test: off
