language: java
jdk:
  - openjdk8
sudo: required
os:
  - linux
dist: xenial
install: 
    - sudo apt-get update
    - sudo apt-get install python3
    - sudo rm -f /usr/bin/python && sudo ln -s $(which python3) /usr/bin/python
    - wget https://bootstrap.pypa.io/get-pip.py
    - sudo python3 get-pip.py
    - sudo python3 -m pip install mkdocs
    - sudo python3 -m pip install mkdocs-material
script:
    - ./gradlew buildJar buildWar buildCli buildDoc buildDocker -PbuildNumber=${TRAVIS_JOB_NUMBER} ${CLIENT_PATH}
    - ./gradlew jacocoTestReport
after_success:
    - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: DEMO_PATH=${DEMO_PATH}/dev && ./publish.sh
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: ./publish.sh
    on:
      branch: master
