language: java
sudo: required
os:
  - linux
dist: trusty
install: 
    - sudo apt-get install --only-upgrade python
    - wget https://bootstrap.pypa.io/get-pip.py
    - sudo python get-pip.py
    - sudo pip install mkdocs
    - sudo pip install mkdocs-material
script:
    - ./gradlew buildJar buildWar buildCli buildDoc buildDocker -PbuildNumber=${TRAVIS_JOB_NUMBER} ${CLIENT_PATH} && ./e2e/integration_tests.sh
    - ./gradlew jacocoTestReport
after_success:
    - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: DEMO_PATH=${DEMO_PATH}/dev && ./publish.sh
    on:
      branch: develop
  - provider: script
    skip_cleanup: true
    script: ./publish.sh
    on:
      branch: master
